FROM python:3.10

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg libgl1 libsm6 && \
    rm -rf /var/lib/apt/lists/*

COPY ../whisper/requirements.txt .
RUN pip install -r requirements.txt

COPY ../whisper/main.py .

EXPOSE 8901

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8901"]
