FROM gradle:8.4.0-jdk17 AS builder

WORKDIR /app
COPY TelegramBot/ ./TelegramBot/

WORKDIR /app/TelegramBot
RUN gradle clean bootJar --no-daemon


FROM eclipse-temurin:17-jdk

EXPOSE 1805
WORKDIR /app

COPY --from=builder /app/TelegramBot/build/libs/*.jar telegramBot.jar

ENTRYPOINT ["java", "-jar", "telegramBot.jar"]
