FROM vllm/vllm-openai

WORKDIR /model

RUN apt-get update && apt-get install -y git-lfs \
  && git lfs install \
  && git clone https://huggingface.co/Qwen/Qwen3-1.7B \
  && cd Qwen3-1.7B && git lfs pull

EXPOSE 8000

CMD ["python3", "-m", "vllm.entrypoints.openai.api_server", \
  "--model", "/model/Qwen3-1.7B", \
  "--dtype", "float16", \
  "--gpu-memory-utilization", "0.75", \
  "--max-model-len", "8192", \
  "--port", "8000"]
