FROM gradle:8.4.0-jdk17 AS builder

WORKDIR /app
COPY LifePilot/ ./LifePilot/

WORKDIR /app/LifePilot
RUN gradle clean bootJar --no-daemon


FROM eclipse-temurin:17-jdk

EXPOSE 1804
WORKDIR /app

COPY --from=builder /app/LifePilot/build/libs/*.jar server.jar

ENTRYPOINT ["java", "-jar", "server.jar"]
